- assets/scss/components/article-series.scss
- assets/scss/meet-the-team.scss
- views/helpers/image.js
We launched the new image service 6 days ago, I'm currently going around FT projects and helping them migrate to it.
The new Image Service includes a lot of improvements:
- The application is multi-region with failover
- We use stale-on-error and stale-while-revalidate cache extensions to ensure users get stale content if the application errors or has to revalidate an image
- We serve much smaller WebP and JPEG XR images to supported browsers
- We’ve seen a reduction in file size for a large number of image requests
- We’re now serving images over H2
> use new image service

- lib/controllers/articleCtrl.js
We have discrovered that Alphaville Fastly configuration is stripping off all cookies from the request. Therefore the next-flags cookie was not making its way up to the article controller.
To fix this;
* Updated the Fastly configuration to write the contents of the next-flags cookie into a request header named next-flags.
* Updated the article controller to use the value from the header instead of the cookie.
> Fix o-comments-beta not displaying in production

- assets/js/article.js
- lib/controllers/articleCtrl.js
- views/article.handlebars
For articles published after a certain date (which is not decided yet) we will start using Coral Talk.
This relies on two environment variables named COMMENTS_USE_CORAL_TALK and COMMENTS_USE_CORAL_MILESTONE_DATE.
COMMENTS_USE_CORAL_TALK needs to be set to `true` for this to work.
COMMENTS_USE_CORAL_MILESTONE_DATE defines at which point we start using Coral Talk. Articles published before that date will be rendered with Livefyre, and those that are published after that date will be rendered with Coral.
If COMMENTS_USE_CORAL_TALK is not true or COMMENTS_USE_CORAL_MILESTONE_DATE is not set, the page will render with Livefyre.
> Show Coral Talk for articles published after migration start date

- bower.json
- views/article.handlebars
This will allow us to get Coral v5 in Alphaville. It will only be available behind the `coralTalkReplacement` flag.
> Bump o-comments-beta to v6.0.0-beta.12

- routes/__access_metadata.js
So:
* access.ft.com uses ftalphaville.ft.com/__access-metadata to determine if a URL is free
* ftalphaville.ft.com/__access-metadata uses Wordpress's /__access-metadata to generate itself.
* Wordpress is no longer used for Alphaville 😬 
* Therefore Spark-created articles can't be made free.
This is obviously a hack. Making Alphaville articles free is very rare - but hard coding this one will allow them to get this one promotional article free.
> HACK: make one particular Alphaville article free

- bower.json
We are going to delete `next-comments-auth-service` in favour of `next-comments-api`. With this update, o-comments-beta will use `next-comments-api` for authenticating users.
> Update o-comments-beta version to v6.0.0-beta.17

- assets/js/article.js
- bower.json
See https://jira.ft.com/browse/ADSDEV-83
As part of removing Krux from Alphaville:
- Pin dependency to `alphaville-ui@2.4.0`
- Import `oAds` using import instead of require since `oAds@11`
> ADSDEV-83 Remove Krux from Alphaville

- assets/js/article.js
- bower.json
- lib/controllers/articleCtrl.js
- views/article.handlebars
Stories that are older than the `COMMENTS_USE_CORAL_MILESTONE_DATE` will
render `o-comments` v5 while stories after that date will render
`o-comments` v6.
To test, set `COMMENTS_USE_CORAL_TALK=true` and `COMMENTS_USE_CORAL_MILESTONE_DATE=2019-09-25T00:00:00.000Z` in the `.env` file. Then run the app locally and you should see Coral rendered on articles published today and Livefyre rendered on articles published yesterday.
> Split service between Livefyre and Coral Talk

- lib/controllers/articleCtrl.js
By adding the useCoralTalk querystring you will be able to see the new
beta comments in production.
> Allow beta comments to be tested in prod via query string

- assets/js/article.js
- assets/js/common.js
- assets/js/permutive.js
- bower.json
This is part of Jira ticket [#226 Alphaville - Pageview event not passed to Permutive](https://financialtimes.atlassian.net/browse/ADSDEV-226?atlOrigin=eyJpIjoiY2I4ZGE3MzY1MGZlNDZiY2ExMWM4NTg5Y2ZlOWM5MzQiLCJwIjoiaiJ9ADSDEV-226)
See also related PR [alphaville-ui #14](https://github.com/Financial-Times/alphaville-ui/pull/14)
`Permutive` is not working properly on Alphaville, specifically it is not firing the `PageView` event from Alphaville.
Set user and page metadata in `common.js`.
> ADSDEV-226 Set user and page metadata in common.js

- views/article.handlebars
Pass the same url on the front end as the url thats created by the
lambda which creates articles in Coral.
Related to this PR Financial-Times/comments-new-article-listener#10
> Use the canonical url for comments

- views/partials/comment-counter.handlebars
- views/partials/grid-cards/card-alphachat.handlebars
- views/partials/grid-cards/card-blog.handlebars
- views/partials/grid-cards/card-firstft.handlebars
- views/partials/grid-cards/card-hero.handlebars
- views/partials/grid-cards/card-imagelead.handlebars
- views/partials/grid-cards/card-marketslive.handlebars
- views/partials/grid-cards/card-opinion.handlebars
- views/partials/list-cards/card-firstft.handlebars
- views/partials/list-cards/card-generic.handlebars
- views/partials/list-cards/card-marketslive.handlebars
We're unable to render both the Coral and Livefyre comment counts
on the Blogs stream page because `o-comments` v5 conflicts with v6.
While we are in the process of migrating to Coral, we are temporarily
removing the comment count. Once migration is complete, we will render
the Coral comment count.
Before:
After:
> Remove comment count from Blogs stream page

- assets/scss/components/article-page.scss
- bower.json
- views/article.handlebars
Bumps o-comments to the latest and ~applies the styles~ for "signed in as" prompt.
No need to apply styles anymore. With o-comments#7.1.4, they come for free.
> Edit display name

- assets/scss/components/article-page.scss
- lib/controllers/articleCtrl.js
- views/article.handlebars
When there is a technical issue with the comments, we want to display our users a friendly message instead of an error message or half loaded comments component.
When the environment variable is set `COMMENTS_MAINTENANCE_MODE=true` this message will be displayed:
> Comments maintenance mode

- lib/controllers/articleCtrl.js
- views/article.handlebars
Livefyre service will stop at the end of 2019
In case we can't we can't complete comments migration we want to display a message in all Livefyre articles after the start 2020.
> Comments migration message

- views/article.handlebars
This copy should only appear after 1/1/2020 and only on articles published before 28 October.
> Update migration message copy

- lib/services/sessionApi.js
FT Core are deploying breaking changes in January 2020 which will deprecate the old api key syntax.
[Trello card](https://trello.com/c/KlYE2sSK/139-breaking-change-replace-where-ftapikey-header-is-used)
> Migrate FT_Api_Key request header to FT-Api-Key

- bin/www
- lib/controllers/marketsliveCtrl.js
- lib/services/article.js
- lib/utils/marketsLiveArticles.js
The content needed for the Markets Live homepage is already available in
the archived Markets Live sessions so there's no need to get that info
from alphaville-es-interface-service.
This work came out of the need to remove the Markets Live API from
alphaville-es-interface-service. Fingers crossed, it should now be
easier to do that.
This work is related to the ongoing decommissioning of Markets Live,
see https://github.com/Financial-Times/next/issues/400.
> Load MarketsLive homepage content from file system

- README.md
- app.js
- package.json
This work is related to the ongoing decommissioning of Markets Live,
see Financial-Times/next#400.
> Remove Markets Live API

- lib/health/healthServices/emailService.js
- lib/services/email.js
* Replace Email Service url
The email service has changed its url to ep.ft.com, and the current endpoint
"https://email-webservices.ft.com/users/{userId}?product=alphaville2" is no
longer live. This change renames the envvar and  replaces its value to hit the endpoint
"https://ep.ft.com/users-lists/users/:userUuid".
That endpoint is used to retrieve the user's email here:
https://github.com/Financial-Times/alphaville-blogs/blob/master/lib/middlewares/restrictedAccess.js#L43
and the email platform's API docs:
https://ep.ft.com/docs/users-lists/#api-User-GetUser indicate that the above
endpoint is the one that will return the user's email address.
* Authenticate with token
The email platform team has indicated that's their preferred way for us to
authenticate as it helps them track which …
> Update url and auth header for call to email platform API

- routes/__access_metadata.js
This endpoint is used by access service. Membership team requested us to review the cache policy for it.
Since the response is quite static in nature, we want to put a long cache for this endpoint.
> Add cache control to __access_metadata endpoint

- assets/js/permutive.js
- bower.json
- package-lock.json
- package.json
Part of Jira [ADSDEV-449 Use n-permutive for alphaville][ADSDEV-449]
We are now using directly `n-permutive`, instead of the helper module `permutive` exported via alphaville-ui, which was a wrapper around `o-permutive`.
It awaits for oAds's `initialised` event to be thrown, in order to access the targeting exposed by oAds and then identifying the user and track the PageView
Depends on `alphaville@5.x`, which includes this changes https://github.com/Financial-Times/alphaville-ui/pull/27
[ADSDEV-449]: https://financialtimes.atlassian.net/browse/ADSDEV-449
> ADSDEV-449 Use n-permutive for Alphaville

- lib/controllers/articleCtrl.js
- views/article.handlebars
Since the comments data migration from Livefyre to Coral is complete, we can remove the migration message and cleanup the related logic.
> Remove comments migration code

- assets/js/common.js
- assets/js/permutive.js
- package-lock.json
- package.json
[ADSDEV-407][ADSDEV-407]
Use the latest `n-permutive@2.4.0`, which adds permutive's view-id to ads targeting.
Also listen to event `oAds.initialised` before running any code that relies on oAds.
[ADSDEV-407]: https://financialtimes.atlassian.net/browse/ADSDEV-407
> ADSDEV-407 Update to n-permutive@2.4.0

- assets/scss/components/article-content-body/partials/_images.scss
If alphaville insert responsive images from charts (as they can now in Spark), the image isn't restricted at all, so expands to the size of the image.
This change applies the same styles as n-content-image, to restrict the width of the image inside picture elements.
> Handle picture elements

- lib/health/healthServices/emailService.js
This healthcheck was failing as the uuid of the user belongs to a former FT
employee or contractor so the email service doesn't know about them anymore. 
The new uuid belongs to a test premium user we use in
next-test-sessions-lambda so more reliable. When running the request in Postman
with that uuid, it returns a 200 so should work!
https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1137&projectKey=NOPS&modal=detail&selectedIssue=NOPS-332
> Fix email service severity 3 healthcheck

- assets/js/permutive.js
- package.json
[ADSDEV-603][ADSDEV-603]
Ads Data Ops wants to identify a user in the Permutive realm only by `guid`.
This PR requires to upgrade from `n-permutive@2.x` to the latest version of `n-permutive@3.x`, which has updated the exposed functionalities. Specifically, `trackPageView()` now accepts data in Permutive's schema format.
Alphaville apps are still using o-ads@14, which caches the Ads API responses and exposes them through `ads.api.data`.
This work is based on [n-permutive][n-permutive]'s guide to [How to use an Ads Data Formatter][permutive_using_formatter] - specifically the example on using the Ads Data V1 formatter.
[ADSDEV-603]: https://financialtimes.atlassian.net/browse/ADSDEV-603
[n-permutive]: https://github.com/Financial-Times/n-permutive
[permutive_using_formatter]: …
> ADSDEV-603 Permutive: identify User only by GUID

- assets/js/permutive.js
Fix a mistake where user.guid was read instead of user.uuid
> ADSDEV-603: Set uuid instead of guid
